import React from 'react';
import PanelDetailLayout from '../components/PanelDetailLayout';

export default function PanelsAPFC() {
  const specifications = [
    { label: 'Capacitor Bank System Rating', value: '25 kVAr to 1000+ kVAr Modular Banks' },
    { label: 'Power Factor Target Accuracy', value: '0.99 Lagging to Unity (Programmable)' },
    { label: 'Capacitor Switching Mechanism', value: 'Thyristor Zero-Crossing / Capacitor Contactors' },
    { label: 'Harmonic Detuned Reactors', value: 'Integrated 7% / 14% Copper Finned Reactors' },
    { label: 'Dynamic Response Time', value: '<20ms Instantaneous Thyristor Switching' },
    { label: 'Capacitor Dielectric Type', value: 'Heavy Duty MPP Cylindrical / Square Gas-Filled' },
    { label: 'Controller Standard', value: '12 / 16 Stage Intelligent Microprocessor Relay' }
  ];

  const features = [
    { title: 'Electricity Penalty Elimination', desc: 'Automatically boosts sagging plant power factor to 0.99+, permanently saving lakhs in utility kVAh billing penalties.' },
    { title: 'Intelligent Capacitor Switching', desc: 'Advanced microprocessor algorithms rotate capacitor steps evenly, preventing leading overcompensation and voltage spikes.' },
    { title: 'Harmonic Resonance Suppression', desc: 'Heavy copper detuned reactors block destructive non-linear harmonic currents generated by VFDs and LED drives.' },
    { title: 'Zero-Transient Thyristor Firing', desc: 'Static solid-state thyristors switch capacitor banks at zero voltage crossing, eliminating dangerous electrical arcing.' }
  ];

  const applications = [
    'Steel Rolling Mills & Induction Furnaces',
    'Textile Spinning & Weaving Manufacturing',
    'Commercial Shopping Complexes & Hotels',
    'Automotive CNC Machining Floors'
  ];

  const images = [
    "/photos/DSC_9590.JPG",
    "/photos/DSC_9583.JPG",
    "/photos/DSC_9599.JPG",
    "/photos/DSC_9584.JPG"
  ];

  return (
    <PanelDetailLayout 
      breadcrumb="APFC Panel"
      category="Electrical Panels"
      categoryPath="/panels"
      title="APFC Panels"
      subtitle="Automatic Power Factor Correction & Penalty Elimination Centers"
      intro="Industrial inductive loads like electric motors and transformers draw massive reactive power (kVAr), causing utility penalties and overheated transformers. APFC panels dynamically inject leading kVAr to maintain unity power factor."
      sustainabilityText="By improving power factor, our APFC panels reduce energy wastage and operational costs. Intelligent capacitor switching prevents overcompensation and extends equipment life. These panels directly contribute to energy conservation and sustainable industrial energy management."
      specifications={specifications}
      features={features}
      applications={applications}
      productImages={images}
    />
  );
}